### ISSUE TITLE
Updating incidents fails with error: 'end_time': 'The field is not allowed to be changed.'

### ISSUE THREAD

**Issue by vv3** [Uninett/pyargus#4] opened 2021-12-21 09:18 UTC
### Code/API request
Using Backend v.1.3.1, API v1(stable), 

I tried this code/API request:

```python
from pyargus.client import Client
from pyargus.models import Incident
c = Client(api_root_url=argus_api_url+"/api/v1", token=argus_token)
incidents = c.get_incidents(source_incident_id="8268")
i = (next(incidents, None))
ipk = i.pk
print(ipk)
i2 = Incident(pk=ipk, level=3)
status = c.update_incident(i2)
print(status)
```

### Expected behaviour

I expected to see this happen: Succesful updating of Incident

### Actual behaviour

Instead, this happened: Gets error 400
```
simple_rest_client.exceptions.ClientError: ("operation=client_error, response=Response(url='https://argus-review-vv-n867l3-api.paas2.uninett.no/api/v1/incidents/21805/', method='PATCH', body={'end_time': 'The field is not allowed to be changed.', 'level': 'The field is not allowed to be changed.'}, headers=Headers({'date': 'Tue, 21 Dec 2021 09:06:13 GMT', 'content-type': 'application/json', 'content-length': '104', 'connection': 'keep-alive', 'vary': 'Accept, Origin', 'allow': 'GET, PUT, PATCH, HEAD, OPTIONS', 'x-frame-options': 'DENY', 'x-content-type-options': 'nosniff', 'referrer-policy': 'same-origin'}), status_code=400, client_response=<Response [400 Bad Request]>)", Response(url='https://argus-review-vv-n867l3-api.paas2.uninett.no/api/v1/incidents/21805/', method='PATCH', body={'end_time': 'The field is not allowed to be changed.', 'level': 'The field is not allowed to be changed.'}, headers=Headers({'date': 'Tue, 21 Dec 2021 09:06:13 GMT', 'content-type': 'application/json', 'content-length': '104', 'connection': 'keep-alive', 'vary': 'Accept, Origin', 'allow': 'GET, PUT, PATCH, HEAD, OPTIONS', 'x-frame-options': 'DENY', 'x-content-type-options': 'nosniff', 'referrer-policy': 'same-origin'}), status_code=400, client_response=<Response [400 Bad Request]>))
```
I am aware that updating `level` is not supported yet, but this error is not about that.  

Even though I didn't supply `end_time` the backend complains that changing it is not allowed.

**Comment by lunkwill42** [comment] 2022-02-07 13:23
This is confirmed to be an issue with PyArgus - it's basically a regression stemming from the fix for #3 . A fix for this might be tricky, since we need to keep track of the difference between `end_time` being `None` because the value was never set and `end_time` being `None` because it was set so explicitly...

**Closed** 2022-02-10 13:25 UTC
